import json

def generate_database():
    print("Generating comprehensive Starshelf database...")
    
    books = [
        {
            "title": "Ancillary Justice",
            "author": "Ann Leckie",
            "year": "2013",
            "isbn": "9780316246620",
            "genre": "Science Fiction",
            "mood": "Hard Sci-Fi",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Winner, Nebula Winner",
            "series_info": "Book 1 of Imperial Radch",
            "print_rating": 4.6,
            "audio_rating": 4.8,
            "summary": "A brilliant space opera following Breq, a former warship trapped in a human body, seeking vengeance against the ruler of an empire.",
            "goodreads": "https://www.goodreads.com/search?q=Ancillary+Justice",
            "libby": "https://libbyapp.com/search/libby/search/query-Ancillary%20Justice"
        },
        {
            "title": "A Memory Called Empire",
            "author": "Arkady Martine",
            "year": "2019",
            "isbn": "9781250186430",
            "genre": "Science Fiction",
            "mood": "Dense World-Building",
            "best_format": "📖 Best in Print",
            "award": "Hugo Winner",
            "series_info": "Book 1 of Teixcalaan",
            "print_rating": 4.7,
            "audio_rating": 4.5,
            "summary": "Ambassador Mahit Dzmare arrives in the heart of the Teixcalaanli Empire only to discover her predecessor was murdered.",
            "goodreads": "https://www.goodreads.com/search?q=A+Memory+Called+Empire",
            "libby": "https://libbyapp.com/search/libby/search/query-A%20Memory%20Called%20Empire"
        },
        {
            "title": "Jonathan Strange & Mr Norrell",
            "author": "Susanna Clarke",
            "year": "2004",
            "isbn": "9780765356154",
            "genre": "Fantasy",
            "mood": "Epic Scale",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Winner, World Fantasy Winner",
            "series_info": "Standalone Novel",
            "print_rating": 4.5,
            "audio_rating": 4.9,
            "summary": "Set in 19th-century England during the Napoleonic Wars, two men bring back practical magic with vastly different philosophies.",
            "goodreads": "https://www.goodreads.com/search?q=Jonathan+Strange+and+Mr+Norrell",
            "libby": "https://libbyapp.com/search/libby/search/query-Jonathan%20Strange"
        },
        {
            "title": "American Gods",
            "author": "Neil Gaiman",
            "year": "2001",
            "isbn": "9780062572233",
            "genre": "Fantasy",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Winner, Nebula Winner, World Fantasy Winner",
            "series_info": "Book 1 of American Gods",
            "print_rating": 4.6,
            "audio_rating": 4.9,
            "summary": "Released from prison, Shadow Moon finds himself employed by the mysterious Mr. Wednesday as a war brews between old and new gods.",
            "goodreads": "https://www.goodreads.com/search?q=American+Gods",
            "libby": "https://libbyapp.com/search/libby/search/query-American%20Gods"
        },
        {
            "title": "The Ocean at the End of the Lane",
            "author": "Neil Gaiman",
            "year": "2013",
            "isbn": "9780062255655",
            "genre": "Fantasy",
            "mood": "Character-Driven",
            "best_format": "📖 Best in Print",
            "award": "World Fantasy Winner",
            "series_info": "Standalone Novel",
            "print_rating": 4.5,
            "audio_rating": 4.7,
            "summary": "A middle-aged man returns to his childhood home and remembers supernatural forces he encountered alongside the enigmatic Hempstock family.",
            "goodreads": "https://www.goodreads.com/search?q=The+Ocean+at+the+End+of+the+Lane",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Ocean+at+the+End+of+the+Lane"
        },
        {
            "title": "The Goblin Emperor",
            "author": "Katherine Addison",
            "year": "2014",
            "isbn": "9780765365705",
            "genre": "Fantasy",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Nominee, Nebula Nominee, World Fantasy Nominee",
            "series_info": "Standalone Novel",
            "print_rating": 4.6,
            "audio_rating": 4.8,
            "summary": "The half-goblin fourth son of the Emperor unexpectedly inherits the throne after a tragedy, navigating court intrigue with profound empathy.",
            "goodreads": "https://www.goodreads.com/search?q=The+Goblin+Emperor",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Goblin+Emperor"
        },
        {
            "title": "The City & The City",
            "author": "China Miéville",
            "year": "2009",
            "isbn": "9780345458460",
            "genre": "Science Fiction",
            "mood": "Hard Sci-Fi",
            "best_format": "📖 Best in Print",
            "award": "Hugo Winner, World Fantasy Nominee",
            "series_info": "Standalone Novel",
            "print_rating": 4.4,
            "audio_rating": 4.6,
            "summary": "A murder investigation crosses the border between two overlapping European city-states that occupy the exact same geographic space.",
            "goodreads": "https://www.goodreads.com/search?q=The+City+%26+The+City",
            "libby": "https://libbyapp.com/search/libby/search/query-The+City+and+The+City"
        },
        {
            "title": "The Fifth Season",
            "author": "N.K. Jemisin",
            "year": "2015",
            "isbn": "9780316229296",
            "genre": "Fantasy",
            "mood": "Epic Scale",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Winner",
            "series_info": "Book 1 of The Broken Earth",
            "print_rating": 4.8,
            "audio_rating": 4.9,
            "summary": "In a world wracked by catastrophic climate shifts, a mother with the power to control the earth searches for her kidnapped daughter.",
            "goodreads": "https://www.goodreads.com/search?q=The+Fifth+Season",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Fifth+Season"
        },
        {
            "title": "Dune",
            "author": "Frank Herbert",
            "year": "1965",
            "isbn": "9780441172719",
            "genre": "Science Fiction",
            "mood": "Epic Scale",
            "best_format": "📖 Best in Print",
            "award": "Hugo Winner, Nebula Winner",
            "series_info": "Book 1 of Dune",
            "print_rating": 4.9,
            "audio_rating": 4.7,
            "summary": "Set on the desert planet Arrakis, young Paul Atreides finds his family thrust into a deadly battle for control of the galaxy's most valuable resource.",
            "goodreads": "https://www.goodreads.com/search?q=Dune",
            "libby": "https://libbyapp.com/search/libby/search/query-Dune"
        },
        {
            "title": "The Left Hand of Darkness",
            "author": "Ursula K. Le Guin",
            "year": "1969",
            "isbn": "9780441478125",
            "genre": "Science Fiction",
            "mood": "Dense World-Building",
            "best_format": "📖 Best in Print",
            "award": "Hugo Winner, Nebula Winner",
            "series_info": "Hainish Cycle",
            "print_rating": 4.5,
            "audio_rating": 4.4,
            "summary": "A lone human envoy is sent to the icebound planet Gethen to convince its ambisexual inhabitants to join a peaceful interstellar confederation.",
            "goodreads": "https://www.goodreads.com/search?q=The+Left+Hand+of+Darkness",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Left+Hand+of+Darkness"
        },
        {
            "title": "Hyperion",
            "author": "Dan Simmons",
            "year": "1989",
            "isbn": "9780553283685",
            "genre": "Science Fiction",
            "mood": "Epic Scale",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Winner",
            "series_info": "Book 1 of Hyperion Cantos",
            "print_rating": 4.7,
            "audio_rating": 4.8,
            "summary": "On the eve of Armageddon, seven pilgrims journey to the Time Tombs on the planet Hyperion, each sharing their dark and interwoven tales.",
            "goodreads": "https://www.goodreads.com/search?q=Hyperion",
            "libby": "https://libbyapp.com/search/libby/search/query-Hyperion"
        },
        {
            "title": "A Fire Upon the Deep",
            "author": "Vernor Vinge",
            "year": "1992",
            "isbn": "9780312852238",
            "genre": "Science Fiction",
            "mood": "Hard Sci-Fi",
            "best_format": "📖 Best in Print",
            "award": "Hugo Winner",
            "series_info": "Zones of Thought",
            "print_rating": 4.5,
            "audio_rating": 4.3,
            "summary": "Humanity accidentally unleashes an ancient, malignant intelligence across the galaxy, and survival depends on a remote planet populated by hive-mind aliens.",
            "goodreads": "https://www.goodreads.com/search?q=A+Fire+Upon+the+Deep",
            "libby": "https://libbyapp.com/search/libby/search/query-A+Fire+Upon+the+Deep"
        },
        {
            "title": "Station Eleven",
            "author": "Emily St. John Mandel",
            "year": "2014",
            "isbn": "9780385535388",
            "genre": "Science Fiction",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Arthur C. Clarke Award Winner",
            "series_info": "Standalone Novel",
            "print_rating": 4.4,
            "audio_rating": 4.7,
            "summary": "A moving post-apocalyptic novel following a troupe of actors and musicians wandering the wasteland of a civilization devastated by a flu pandemic.",
            "goodreads": "https://www.goodreads.com/search?q=Station+Eleven",
            "libby": "https://libbyapp.com/search/libby/search/query-Station+Eleven"
        },
        {
            "title": "Children of Time",
            "author": "Adrian Tchaikovsky",
            "year": "2015",
            "isbn": "9781447273308",
            "genre": "Science Fiction",
            "mood": "Hard Sci-Fi",
            "best_format": "🎧 Best on Audio",
            "award": "Arthur C. Clarke Award Winner",
            "series_info": "Book 1 of Children of Time",
            "print_rating": 4.7,
            "audio_rating": 4.9,
            "summary": "The last remnants of the human race span the stars searching for a new home, only to find a terraformed world dominated by evolving, sentient spiders.",
            "goodreads": "https://www.goodreads.com/search?q=Children+of+Time",
            "libby": "https://libbyapp.com/search/libby/search/query-Children+of+Time"
        },
        {
            "title": "Embassytown",
            "author": "China Miéville",
            "year": "2011",
            "isbn": "9780345524503",
            "genre": "Science Fiction",
            "mood": "Dense World-Building",
            "best_format": "📖 Best in Print",
            "award": "Arthur C. Clarke Nominee",
            "series_info": "Standalone Novel",
            "print_rating": 4.2,
            "audio_rating": 4.4,
            "summary": "Avice Benner Cho returns to a remote colonial city on the edge of space where humans communicate with native aliens using a language without metaphor.",
            "goodreads": "https://www.goodreads.com/search?q=Embassytown",
            "libby": "https://libbyapp.com/search/libby/search/query-Embassytown"
        },
        {
            "title": "Red Rising",
            "author": "Pierce Brown",
            "year": "2014",
            "isbn": "9780345539786",
            "genre": "Science Fiction",
            "mood": "Epic Scale",
            "best_format": "🎧 Best on Audio",
            "award": "Goodreads Choice Award Winner",
            "series_info": "Book 1 of Red Rising",
            "print_rating": 4.6,
            "audio_rating": 4.9,
            "summary": "Darrow is a low-mining Red working beneath the surface of Mars who infiltrates the ruling Gold caste to bring down a corrupt interplanetary society from within.",
            "goodreads": "https://www.goodreads.com/search?q=Red+Rising",
            "libby": "https://libbyapp.com/search/libby/search/query-Red+Rising"
        },
        {
            "title": "The Three-Body Problem",
            "author": "Cixin Liu",
            "year0": "2008",
            "year": "2008",
            "isbn": "9780765377067",
            "genre": "Science Fiction",
            "mood": "Hard Sci-Fi",
            "best_format": "📖 Best in Print",
            "award": "Hugo Winner",
            "series_info": "Book 1 of Remembrance of Earth's Past",
            "print_rating": 4.4,
            "audio_rating": 4.3,
            "summary": "Against the backdrop of China's Cultural Revolution, a secret military project sends signals into space, establishing contact with an alien civilization facing imminent doom.",
            "goodreads": "https://www.goodreads.com/search?q=The+Three-Body+Problem",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Three-Body+Problem"
        },
        {
            "title": "Piranesi",
            "author": "Susanna Clarke",
            "year": "2020",
            "isbn": "9781526622426",
            "genre": "Fantasy",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Women's Prize for Fiction Winner",
            "series_info": "Standalone Novel",
            "print_rating": 4.6,
            "audio_rating": 4.8,
            "summary": "Piranesi lives in the House, an infinite labyrinthine structure filled with thousands of statues, ocean tides crashing through halls, and a mysterious companion known as the Other.",
            "goodreads": "https://www.goodreads.com/search?q=Piranesi",
            "libby": "https://libbyapp.com/search/libby/search/query-Piranesi"
        },
        {
            "title": "The Priory of the Orange Tree",
            "author": "Samantha Shannon",
            "year": "2019",
            "isbn": "9781635570298",
            "genre": "Fantasy",
            "mood": "Epic Scale",
            "best_format": "📖 Best in Print",
            "award": "British Fantasy Award Nominee",
            "series_info": "Roots of Chaos",
            "print_rating": 4.5,
            "audio_rating": 4.4,
            "summary": "An epic feminist high fantasy spanning divided empires, court intrigue, dragon riders, and an awakening ancient terror threatening the world.",
            "goodreads": "https://www.goodreads.com/search?q=The+Priory+of+the+Orange+Tree",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Priory+of+the+Orange+Tree"
        },
        {
            "title": "The Way of Kings",
            "author": "Brandon Sanderson",
            "year": "2010",
            "isbn": "9780765326353",
            "genre": "Fantasy",
            "mood": "Epic Scale",
            "best_format": "🎧 Best on Audio",
            "award": "Audie Award Winner",
            "series_info": "Book 1 of The Stormlight Archive",
            "print_rating": 4.9,
            "audio_rating": 5.0,
            "summary": "On Roshar, a world torn apart by magical storms and endless war, a fallen soldier, a young scholar, and a burdened prince cross paths as ancient powers awaken.",
            "goodreads": "https://www.goodreads.com/search?q=The+Way+of+Kings",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Way+of+Kings"
        },
        {
            "title": "The Name of the Wind",
            "author": "Patrick Rothfuss",
            "year": "2007",
            "isbn": "9780756404746",
            "genre": "Fantasy",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Quill Award Winner",
            "series_info": "Book 1 of The Kingkiller Chronicle",
            "print_rating": 4.7,
            "audio_rating": 4.9,
            "summary": "The tale of Kvothe from his childhood in a troupe of traveling players to his years as an infamous wizard and fugitive.",
            "goodreads": "https://www.goodreads.com/search?q=The+Name+of+the+Wind",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Name+of+the+Wind"
        },
        {
            "title": "The Long Way to a Small, Angry Planet",
            "author": "Becky Chambers",
            "year": "2014",
            "isbn": "9781444798983",
            "genre": "Science Fiction",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Kobo Book Award Winner",
            "series_info": "Book 1 of Wayfarers",
            "print_rating": 4.5,
            "audio_rating": 4.7,
            "summary": "A cozy, character-focused space opera following the multi-species crew of a tunneling ship punching wormholes through the galaxy.",
            "goodreads": "https://www.goodreads.com/search?q=The+Long+Way+to+a+Small,+Angry+Planet",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Long+Way+to+a+Small+Angry+Planet"
        },
        {
            "title": "All Systems Red",
            "author": "Martha Wells",
            "year": "2017",
            "isbn": "9780765507581",
            "genre": "Science Fiction",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "Hugo Winner, Nebula Winner",
            "series_info": "Book 1 of The Murderbot Diaries",
            "print_rating": 4.7,
            "audio_rating": 4.9,
            "summary": "A self-hacking security android that has disabled its governor module just wants to spend its days watching soap operas in peace, but humans keep needing protection.",
            "goodreads": "https://www.goodreads.com/search?q=All+Systems+Red",
            "libby": "https://libbyapp.com/search/libby/search/query-All+Systems+Red"
        },
        {
            "title": "The Lies of Locke Lamora",
            "author": "Scott Lynch",
            "year": "2006",
            "isbn": "9780553588941",
            "genre": "Fantasy",
            "mood": "Character-Driven",
            "best_format": "🎧 Best on Audio",
            "award": "World Fantasy Nominee",
            "series_info": "Book 1 of Gentlemen Bastards",
            "print_rating": 4.6,
            "audio_rating": 4.9,
            "summary": "Locke Lamora leads a small band of thieves known as the Gentlemen Bastards, pulling off elaborate heists in a Venice-inspired fantasy city.",
            "goodreads": "https://www.goodreads.com/search?q=The+Lies+of+Locke+Lamora",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Lies+of+Locke+Lamora"
        },
        {
            "title": "The Broken Kingdoms",
            "author": "N.K. Jemisin",
            "year": "2012",
            "isbn": "9780316043953",
            "genre": "Fantasy",
            "mood": "Dense World-Building",
            "best_format": "📖 Best in Print",
            "award": "David Gemmell Award Nominee",
            "series_info": "Book 2 of Inheritance Trilogy",
            "print_rating": 4.4,
            "audio_rating": 4.6,
            "summary": "Ten years after the events of The Hundred Thousand Kingdoms, a new threat arises involving corrupted divine magic and political betrayal in City-Sky.",
            "goodreads": "https://www.goodreads.com/search?q=The+Broken+Kingdoms",
            "libby": "https://libbyapp.com/search/libby/search/query-The+Broken+Kingdoms"
        }
    ]

    with open('books.json', 'w', encoding='utf-8') as f:
        json.dump(books, f, indent=4)
        
    print(f"Successfully generated database with {len(books)} books!")

if __name__ == "__main__":
    generate_database()